import { Platform, StyleSheet } from 'react-native'
import {
  colors,
  radius,
  softShadow,
  spacing,
  typography,
} from './theme'

export const commonStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  content: {
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 1180 : undefined,
    alignSelf: Platform.OS === 'web' ? 'center' : undefined,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: 116,
    gap: spacing.lg,
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing.lg,
    ...softShadow,
  },
  elevatedCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.xl,
    padding: spacing.xl,
    ...softShadow,
  },
  title: { color: colors.text, ...typography.title },
  subtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  sectionTitle: { color: colors.text, ...typography.section },
  label: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 7,
  },
  input: {
    width: '100%',
    minHeight: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    color: colors.text,
  },
  button: {
    minHeight: 52,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: spacing.lg,
  },
  buttonText: { color: colors.navy, fontWeight: '900' },
  secondaryButton: {
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryMist,
  },
  secondaryButtonText: { color: colors.primary, fontWeight: '900' },
  info: {
    color: colors.primaryDark,
    backgroundColor: colors.primarySoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.primaryMist,
    padding: spacing.md,
  },
  error: {
    color: colors.danger,
    backgroundColor: colors.dangerSoft,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FFE4E6',
    padding: spacing.md,
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  spaceBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
})
