import { useRouter } from 'expo-router'
import { ArrowRight, BarChart3, Globe2, Home, MapPinned, ShieldCheck, Smartphone, UsersRound, WifiOff } from 'lucide-react-native'
import { useEffect, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { mobileApi } from '../src/api/resources'
import { useAuth } from '../src/auth/AuthContext'
import { usePreferences } from '../src/preferences/PreferencesContext'
import { colors, radius, spacing } from '../src/styles/theme'
import type { PublicOverviewDto } from '../src/types/api'

export default function PublicLanding() {
  const router = useRouter()
  const { user } = useAuth()
  const { t, language, setLanguage } = usePreferences()
  const [overview, setOverview] = useState<PublicOverviewDto | null>(null)
  useEffect(() => { void mobileApi.publicOverview().then(setOverview).catch(() => undefined) }, [])
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.nav}><View style={styles.brand}><View style={styles.logo}><Globe2 color="white" size={22} /></View><View><Text style={styles.brandTitle}>Census Flow</Text><Text style={styles.brandSub}>Population intelligence</Text></View></View><View style={styles.languages}>{(['mg', 'fr', 'en'] as const).map((value) => <Pressable key={value} style={[styles.lang, language === value && styles.langActive]} onPress={() => setLanguage(value)}><Text style={[styles.langText, language === value && styles.langTextActive]}>{value.toUpperCase()}</Text></Pressable>)}</View></View>
    <View style={styles.hero}><View style={styles.heroIcon}><Smartphone color="white" size={60} /><View style={styles.pin}><MapPinned color="white" size={20} /></View></View><Text style={styles.kicker}>{t('publicKicker')}</Text><Text style={styles.title}>{t('publicTitle')}</Text><Text style={styles.text}>{t('publicText')}</Text><Pressable style={styles.cta} onPress={() => router.push(user ? '/(tabs)' : '/login')}><Text style={styles.ctaText}>{user ? t('home') : t('start')}</Text><ArrowRight color="white" size={20} /></Pressable></View>
    <View style={styles.stats}><PublicStat icon={BarChart3} label={t('completedCampaigns')} value={overview?.completedCampaigns ?? 0} /><PublicStat icon={Home} label={t('totalHouseholds')} value={overview?.validatedHouseholds ?? 0} /><PublicStat icon={UsersRound} label={t('totalCitizens')} value={overview?.validatedCitizens ?? 0} /></View>
    <View style={styles.features}><Feature icon={WifiOff} title={t('offlineFirst')} text={t('offlineFirstText')} /><Feature icon={ShieldCheck} title={t('controlledData')} text={t('controlledDataText')} /><Feature icon={BarChart3} title={t('clearDecisions')} text={t('clearDecisionsText')} /></View>
    <Text style={styles.footer}>Census Flow · Madagascar · {new Date().getFullYear()}</Text>
  </ScrollView>
}
function PublicStat({ icon: Icon, label, value }: { icon: typeof BarChart3; label: string; value: number }) { return <View style={styles.stat}><Icon color={colors.primary} size={20} /><Text style={styles.statValue}>{value.toLocaleString()}</Text><Text style={styles.statLabel}>{label}</Text></View> }
function Feature({ icon: Icon, title, text }: { icon: typeof WifiOff; title: string; text: string }) { return <View style={styles.feature}><View style={styles.featureIcon}><Icon color={colors.primary} size={22} /></View><View style={{ flex: 1 }}><Text style={styles.featureTitle}>{title}</Text><Text style={styles.featureText}>{text}</Text></View></View> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingBottom: 40 }, nav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { flexDirection: 'row', alignItems: 'center', gap: 9 }, logo: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, brandTitle: { fontSize: 16, fontWeight: '900', color: colors.text }, brandSub: { fontSize: 9, color: colors.muted }, languages: { flexDirection: 'row', gap: 4 }, lang: { borderRadius: 9, paddingHorizontal: 8, paddingVertical: 7 }, langActive: { backgroundColor: colors.primarySoft }, langText: { fontSize: 9, fontWeight: '800', color: colors.muted }, langTextActive: { color: colors.primary }, hero: { alignItems: 'center', paddingTop: 52, paddingBottom: 30 }, heroIcon: { position: 'relative', width: 150, height: 150, borderRadius: 50, backgroundColor: colors.navy, alignItems: 'center', justifyContent: 'center' }, pin: { position: 'absolute', right: -2, bottom: 13, width: 48, height: 48, borderRadius: 16, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, kicker: { marginTop: 32, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, color: colors.accent }, title: { marginTop: 10, fontSize: 38, lineHeight: 42, fontWeight: '900', letterSpacing: -1.5, color: colors.text, textAlign: 'center' }, text: { marginTop: 14, maxWidth: 360, fontSize: 14, lineHeight: 22, color: colors.muted, textAlign: 'center' }, cta: { marginTop: 26, minHeight: 56, width: '100%', borderRadius: radius.lg, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, ctaText: { color: 'white', fontWeight: '900' }, stats: { flexDirection: 'row', gap: 8, marginBottom: 16 }, stat: { flex: 1, alignItems: 'center', gap: 4, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.white, padding: 12 }, statValue: { color: colors.text, fontSize: 20, fontWeight: '900' }, statLabel: { color: colors.muted, fontSize: 9, textAlign: 'center' }, features: { gap: 12 }, feature: { flexDirection: 'row', gap: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.white, padding: spacing.lg }, featureIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, featureTitle: { fontWeight: '900', color: colors.text }, featureText: { fontSize: 11, lineHeight: 17, color: colors.muted, marginTop: 4 }, footer: { marginTop: 26, textAlign: 'center', fontSize: 10, color: colors.muted } })
