import { CameraView, useCameraPermissions } from 'expo-camera'
import { useRouter } from 'expo-router'
import { Flashlight, X } from 'lucide-react-native'
import { useState } from 'react'
import { Pressable, StyleSheet, Text, View } from 'react-native'
import PrimaryButton from '../src/components/PrimaryButton'
import { colors, spacing } from '../src/styles/theme'
import { usePreferences } from '../src/preferences/PreferencesContext'
export default function ScanScreen(){const router=useRouter();const {t}=usePreferences();const [permission,requestPermission]=useCameraPermissions();const [scanned,setScanned]=useState(false);const [torch,setTorch]=useState(false);if(!permission)return <View style={styles.center}/>;if(!permission.granted)return <View style={styles.permission}><Text style={styles.permissionTitle}>{t('cameraRequired')}</Text><Text style={styles.permissionText}>{t('cameraText')}</Text><PrimaryButton title={t('allowCamera')} onPress={()=>void requestPermission()}/></View>;return <View style={styles.screen}><CameraView style={StyleSheet.absoluteFill} facing="back" enableTorch={torch} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={scanned?undefined:({data})=>{setScanned(true);const match=data.match(/persons\/([0-9a-f-]+)/i);if(match)router.replace({pathname:'/(tabs)/households',params:{personId:match[1]}});else setTimeout(()=>setScanned(false),1200)}}/><Pressable style={styles.close} onPress={()=>router.back()}><X color={colors.white} size={25}/></Pressable><View style={styles.frame}><View style={[styles.corner,styles.tl]}/><View style={[styles.corner,styles.tr]}/><View style={[styles.corner,styles.bl]}/><View style={[styles.corner,styles.br]}/></View><Text style={styles.text}>{t('scanQr')}</Text><Pressable style={styles.flash} onPress={()=>setTorch(v=>!v)}><Flashlight color={torch?colors.warning:colors.white} size={24}/></Pressable></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#000'},center:{flex:1,backgroundColor:'#000'},permission:{flex:1,justifyContent:'center',padding:spacing.xl,gap:16,backgroundColor:colors.white},permissionTitle:{fontSize:23,fontWeight:'900',color:colors.text},permissionText:{color:colors.muted,lineHeight:21},close:{position:'absolute',top:52,left:20,width:44,height:44,borderRadius:22,backgroundColor:'rgba(0,0,0,.45)',alignItems:'center',justifyContent:'center'},frame:{position:'absolute',top:'29%',left:'15%',width:'70%',aspectRatio:1},corner:{position:'absolute',width:52,height:52,borderColor:'#22D3EE'},tl:{left:0,top:0,borderLeftWidth:4,borderTopWidth:4},tr:{right:0,top:0,borderRightWidth:4,borderTopWidth:4},bl:{left:0,bottom:0,borderLeftWidth:4,borderBottomWidth:4},br:{right:0,bottom:0,borderRightWidth:4,borderBottomWidth:4},text:{position:'absolute',bottom:115,alignSelf:'center',color:colors.white,fontWeight:'700'},flash:{position:'absolute',bottom:48,alignSelf:'center',width:52,height:52,borderRadius:26,backgroundColor:'rgba(0,0,0,.5)',alignItems:'center',justifyContent:'center'}})
