import { useFocusEffect, useRouter } from 'expo-router'
import { Cloud, Eye, Pencil, Plus, Search, Trash2, UsersRound, WifiOff } from 'lucide-react-native'
import { useCallback, useMemo, useState } from 'react'
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { mobileApi } from '../../src/api/resources'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import StatusPill from '../../src/components/StatusPill'
import { deleteQueueItem, getQueue, type QueueItem } from '../../src/storage/database'
import { colors, radius, spacing } from '../../src/styles/theme'
import type { CampaignDto, HouseholdDto } from '../../src/types/api'
import { usePreferences } from '../../src/preferences/PreferencesContext'

type Row = { key: string; source: 'local' | 'server'; referenceCode: string; headFullName: string; phone: string; campaignId: string; status: string; local?: QueueItem; server?: HouseholdDto }

export default function HouseholdsScreen() {
  const router = useRouter()
  const { t } = usePreferences()
  const [serverItems, setServerItems] = useState<HouseholdDto[]>([])
  const [localItems, setLocalItems] = useState<QueueItem[]>([])
  const [campaigns, setCampaigns] = useState<CampaignDto[]>([])
  const [campaignId, setCampaignId] = useState('')
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [remote, local, campaignRows] = await Promise.all([mobileApi.households(campaignId || undefined).catch(() => []), getQueue(), mobileApi.campaigns().catch(() => [])]); setServerItems(remote); setLocalItems(local); setCampaigns(campaignRows) } finally { setLoading(false) } }, [campaignId])
  useFocusEffect(useCallback(() => { void load() }, [load]))
  const rows = useMemo<Row[]>(() => {
    const local = localItems.map((item) => ({ key: `local-${item.id}`, source: 'local' as const, referenceCode: item.payload.household.referenceCode, headFullName: item.payload.household.headFullName, phone: item.payload.household.phoneNumber, campaignId: item.payload.campaignId, status: item.status, local: item }))
    const server = serverItems.map((item) => ({ key: `server-${item.id}`, source: 'server' as const, referenceCode: item.referenceCode, headFullName: item.headFullName ?? t('unknownHead'), phone: item.phoneNumber ?? '', campaignId: item.campaignId, status: item.recordStatus, server: item }))
    return [...local, ...server].filter((item) => (!campaignId || item.campaignId === campaignId) && `${item.referenceCode} ${item.headFullName} ${item.phone}`.toLowerCase().includes(search.toLowerCase()))
  }, [campaignId, localItems, search, serverItems])
  const removeLocal = (item: QueueItem) => Alert.alert(t('deleteDraftQuestion'), t('deleteDraftText'), [{ text: t('cancel'), style: 'cancel' }, { text: t('delete'), style: 'destructive', onPress: () => void deleteQueueItem(item.id).then(load) }])

  return <View style={styles.screen}><View style={styles.header}><ScreenHeader title={t('households')} subtitle={`${rows.length} ${t('resultCount')} · ${t('localAndSynced')}`} /><View style={styles.search}><Search color={colors.muted} size={18} /><TextInput style={styles.searchInput} placeholder={t('searchHouseholds')} value={search} onChangeText={setSearch} /></View><View style={styles.campaignFilter}><Text style={styles.filterLabel}>{t('campaign')}</Text><FlatList horizontal showsHorizontalScrollIndicator={false} data={[{ id: '', name: t('all') }, ...campaigns]} keyExtractor={(item) => item.id || 'all'} renderItem={({ item }) => <Pressable style={[styles.chip, campaignId === item.id && styles.chipActive]} onPress={() => setCampaignId(item.id)}><Text style={[styles.chipText, campaignId === item.id && styles.chipTextActive]}>{item.name}</Text></Pressable>} /></View></View>{loading ? <ActivityIndicator style={{ marginTop: 40 }} color={colors.primary} /> : <FlatList contentContainerStyle={styles.list} data={rows} keyExtractor={(item) => item.key} ListEmptyComponent={<View style={styles.empty}><UsersRound color={colors.muted} size={38} /><Text style={styles.emptyText}>{t('noHousehold')}</Text></View>} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardHead}>{item.source === 'local' ? <WifiOff color={colors.warning} size={18} /> : <Cloud color={colors.success} size={18} />}<View style={{ flex: 1 }}><Text style={styles.code}>{item.referenceCode}</Text><Text style={styles.name}>{item.headFullName}</Text><Text style={styles.meta}>{item.source === 'local' ? `${item.local?.payload.location.fokontanyName} · ${item.local?.payload.persons.length} ${t('citizenCount')}` : item.phone || t('synced')}</Text></View><StatusPill value={item.source === 'local' ? t('pendingSync') : item.status} /></View><View style={styles.actions}>{item.source === 'local' && item.local ? <><Pressable style={styles.action} onPress={() => router.push({ pathname: '/households/[id]', params: { id: item.local?.id } })}><Eye color={colors.textSoft} size={17} /><Text>{t('details')}</Text></Pressable><Pressable style={styles.action} onPress={() => router.push({ pathname: '/households/new', params: { editId: item.local?.id } })}><Pencil color={colors.primary} size={17} /><Text>{t('edit')}</Text></Pressable><Pressable style={[styles.action, styles.actionDanger]} onPress={() => removeLocal(item.local!)}><Trash2 color={colors.danger} size={17} /><Text>{t('delete')}</Text></Pressable></> : <View style={styles.serverHint}><Cloud color={colors.success} size={15} /><Text>{t('syncedControl')}</Text></View>}</View></View>} />}<View style={styles.fab}><PrimaryButton title={t('newHousehold')} icon={Plus} onPress={() => router.push('/households/new')} /></View></View>
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, header: { padding: spacing.lg, gap: spacing.md }, search: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 9 }, searchInput: { flex: 1, color: colors.text }, campaignFilter: { gap: 7 }, filterLabel: { fontSize: 10, fontWeight: '800', color: colors.muted }, chip: { marginRight: 7, borderWidth: 1, borderColor: colors.border, borderRadius: 999, backgroundColor: colors.white, paddingHorizontal: 12, paddingVertical: 8 }, chipActive: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, chipText: { color: colors.textSoft, fontSize: 10, fontWeight: '700' }, chipTextActive: { color: colors.primary, fontWeight: '900' }, list: { paddingHorizontal: spacing.lg, paddingBottom: 120, gap: 12 }, card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, overflow: 'hidden' }, cardHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 11, padding: spacing.lg }, code: { fontSize: 11, fontWeight: '900', color: colors.primary }, name: { fontSize: 16, fontWeight: '800', color: colors.text, marginTop: 4 }, meta: { fontSize: 11, color: colors.muted, marginTop: 5 }, actions: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.border }, action: { flex: 1, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, actionText: { fontSize: 10 }, actionDanger: { backgroundColor: colors.dangerSoft }, serverHint: { flex: 1, minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingHorizontal: 10 }, empty: { alignItems: 'center', gap: 10, paddingTop: 80 }, emptyText: { color: colors.muted }, fab: { position: 'absolute', left: 16, right: 16, bottom: 12 } })
