import { Plus, Search } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { campaignsApi, dwellingsApi, territoriesApi } from '../api/resources'
import { getErrorMessage } from '../api/http'
import DataTable from '../components/common/DataTable'
import Loader from '../components/common/Loader'
import Modal from '../components/common/Modal'
import PageHeader from '../components/common/PageHeader'
import StatusBadge from '../components/common/StatusBadge'
import { useAsync } from '../hooks/useAsync'
import type { DwellingDto } from '../types/api'
import { formatDate } from '../utils/format'

export default function DwellingsPage() {
  const dwellings = useAsync(() => dwellingsApi.list(), []); const campaigns = useAsync(() => campaignsApi.list(), []); const zones = useAsync(() => territoriesApi.list({ type: 'EnumerationArea' }), [])
  const [search, setSearch] = useState(''); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const filtered = useMemo(() => (dwellings.data ?? []).filter((item) => `${item.referenceCode} ${item.address ?? ''} ${item.localityName ?? ''}`.toLowerCase().includes(search.toLowerCase())), [dwellings.data, search])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const raw = Object.fromEntries(new FormData(event.currentTarget).entries()); const payload = { ...raw, latitude: Number(raw.latitude), longitude: Number(raw.longitude) }; try { await dwellingsApi.create(payload); setOpen(false); await dwellings.reload() } catch (exception) { setError(getErrorMessage(exception)) } }
  return <><PageHeader title="Habitations" subtitle="Localisation et statut des unités d’habitation" actions={<button className="button button--primary" onClick={() => setOpen(true)}><Plus size={17}/>Nouvelle habitation</button>}/><section className="card"><div className="toolbar"><label className="search-box"><Search size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Référence, adresse, localité…"/></label></div>{dwellings.loading ? <Loader/> : <DataTable<DwellingDto> rows={filtered} keyOf={(row) => row.id} columns={[{ key: 'ref', title: 'Référence', render: (row) => <strong>{row.referenceCode}</strong> }, { key: 'location', title: 'Localisation', render: (row) => <div><strong>{row.localityName || '—'}</strong><small className="cell-subtitle">{row.address}</small></div> }, { key: 'gps', title: 'GPS', render: (row) => `${row.latitude.toFixed(5)}, ${row.longitude.toFixed(5)}` }, { key: 'status', title: 'Statut', render: (row) => <StatusBadge value={row.recordStatus}/> }, { key: 'date', title: 'Créée le', render: (row) => formatDate(row.createdAtUtc) }, { key: 'actions', title: 'Actions', render: (row) => <div className="inline-actions">{row.recordStatus === 'Draft' && <button className="link-button" onClick={() => void dwellingsApi.submit(row.id).then(dwellings.reload)}>Soumettre</button>}{row.recordStatus === 'Submitted' && <button className="link-button" onClick={() => void dwellingsApi.validate(row.id).then(dwellings.reload)}>Valider</button>}</div> }]}/>}</section><Modal title="Nouvelle habitation" open={open} onClose={() => setOpen(false)}><form className="form-grid" onSubmit={submit}><label>Campagne<select name="campaignId" required><option value="">Sélectionner</option>{campaigns.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Zone de dénombrement<select name="enumerationAreaId" required><option value="">Sélectionner</option>{zones.data?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Référence<input name="referenceCode" required/></label><label>Localité<input name="localityName"/></label><label className="span-2">Adresse<input name="address"/></label><label>Latitude<input name="latitude" type="number" step="0.000001" required/></label><label>Longitude<input name="longitude" type="number" step="0.000001" required/></label>{error && <div className="form-error span-2">{error}</div>}<div className="form-actions span-2"><button type="button" className="button" onClick={() => setOpen(false)}>Annuler</button><button className="button button--primary">Créer</button></div></form></Modal></>
}
