import { useLocalSearchParams, useRouter } from 'expo-router'
import { ArrowLeft, Edit3, MapPin, Trash2, UserRound, UsersRound } from 'lucide-react-native'
import { useEffect, useState } from 'react'
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import PrimaryButton from '../../src/components/PrimaryButton'
import { deleteQueueItem, getQueueItem, type QueueItem } from '../../src/storage/database'
import { colors, radius, spacing } from '../../src/styles/theme'
import { usePreferences } from '../../src/preferences/PreferencesContext'

export default function LocalHouseholdDetail() {
  const { id } = useLocalSearchParams<{ id: string }>()
  const router = useRouter()
  const { t } = usePreferences()
  const [item, setItem] = useState<QueueItem | null>(null)
  useEffect(() => { if (id) void getQueueItem(id).then(setItem) }, [id])
  if (!item) return <View style={styles.center}><Text>{t('loading')}</Text></View>
  const bundle = item.payload
  const remove = () => Alert.alert(t('deleteDraftQuestion'), t('deleteDraftText'), [{ text: t('cancel'), style: 'cancel' }, { text: t('delete'), style: 'destructive', onPress: () => void deleteQueueItem(item.id).then(() => router.back()) }])
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.top}><Pressable style={styles.back} onPress={() => router.back()}><ArrowLeft color={colors.text} size={20} /></Pressable><View><Text style={styles.title}>{bundle.household.referenceCode}</Text><Text style={styles.subtitle}>{t('localDraftStats')}</Text></View></View><View style={styles.location}><MapPin color={colors.primary} size={22} /><View><Text style={styles.locationTitle}>{bundle.location.fokontanyName}</Text><Text style={styles.locationText}>{bundle.location.communeName} · {bundle.location.districtName} · {bundle.location.regionName}</Text><Text style={styles.locationText}>{bundle.location.latitude.toFixed(6)}, {bundle.location.longitude.toFixed(6)}</Text></View></View><View style={styles.card}><View style={styles.cardTitle}><UsersRound color={colors.primary} size={20} /><Text>{bundle.persons.length} {t('citizenCount')}</Text></View>{bundle.persons.map((person, index) => <View key={person.localId} style={styles.person}>{person.photoUri ? <Image source={{ uri: person.photoUri }} style={styles.photo} /> : <View style={styles.photoEmpty}><UserRound color={colors.muted} size={23} /></View>}<View style={{ flex: 1 }}><Text style={styles.personName}>{index + 1}. {person.firstName} {person.lastName}</Text><Text style={styles.personMeta}>{person.ageYears ?? t('unknownAge')} {t('years')} · {person.sex} · {person.occupation || t('occupationMissing')}</Text><Text style={styles.personMeta}>{person.birthPlace} · {person.relationshipToHead}</Text></View></View>)}</View><PrimaryButton title={t('editDraft')} icon={Edit3} onPress={() => router.replace({ pathname: '/households/new', params: { editId: item.id } })} /><Pressable style={styles.delete} onPress={remove}><Trash2 color={colors.danger} size={18} /><Text>{t('deleteDraft')}</Text></Pressable></ScrollView>
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 40 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, top: { flexDirection: 'row', alignItems: 'center', gap: 12 }, back: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 19, fontWeight: '900', color: colors.text }, subtitle: { fontSize: 10, color: colors.muted }, location: { flexDirection: 'row', gap: 12, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.primarySoft, padding: spacing.lg }, locationTitle: { fontWeight: '900', color: colors.text }, locationText: { marginTop: 3, fontSize: 10, color: colors.textSoft }, card: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, backgroundColor: colors.white, overflow: 'hidden' }, cardTitle: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, person: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, photo: { width: 54, height: 54, borderRadius: 15 }, photoEmpty: { width: 54, height: 54, borderRadius: 15, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' }, personName: { fontWeight: '900', color: colors.text }, personMeta: { fontSize: 10, color: colors.muted, marginTop: 3 }, delete: { minHeight: 50, borderWidth: 1, borderColor: '#F9C4C4', borderRadius: radius.md, backgroundColor: colors.dangerSoft, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, deleteText: { color: colors.danger } })
