import { useFocusEffect, useRouter } from 'expo-router'
import { Plus, Search, UsersRound } from 'lucide-react-native'
import { useCallback, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { mobileApi } from '../../src/api/resources'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import StatusPill from '../../src/components/StatusPill'
import { colors, radius, spacing } from '../../src/styles/theme'
import type { HouseholdDto } from '../../src/types/api'
export default function HouseholdsScreen(){const router=useRouter();const [items,setItems]=useState<HouseholdDto[]>([]);const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{setItems(await mobileApi.households())}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));const filtered=items.filter(item=>`${item.referenceCode} ${item.headFullName??''}`.toLowerCase().includes(search.toLowerCase()));return <View style={styles.screen}><View style={styles.header}><ScreenHeader title="Ménages" subtitle={`${filtered.length} ménage(s)`}/><View style={styles.search}><Search color={colors.muted} size={18}/><TextInput style={styles.searchInput} placeholder="Rechercher un ménage…" value={search} onChangeText={setSearch}/></View></View>{loading?<ActivityIndicator style={{marginTop:40}} color={colors.primary}/>:<FlatList contentContainerStyle={styles.list} data={filtered} keyExtractor={item=>item.id} ListEmptyComponent={<View style={styles.empty}><UsersRound color={colors.muted} size={38}/><Text style={styles.emptyText}>Aucun ménage disponible.</Text></View>} renderItem={({item})=><Pressable style={styles.card}><View style={{flex:1}}><Text style={styles.code}>{item.referenceCode}</Text><Text style={styles.name}>{item.headFullName||'Chef non renseigné'}</Text><Text style={styles.meta}>{item.householdType} · {item.phoneNumber||'Sans téléphone'}</Text></View><StatusPill value={item.recordStatus}/></Pressable>}/>}<View style={styles.fab}><PrimaryButton title="Nouveau ménage" icon={Plus} onPress={()=>router.push('/households/new')}/></View></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},header:{padding:spacing.lg,gap:spacing.lg},search:{minHeight:48,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.white,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:9},searchInput:{flex:1,color:colors.text},list:{paddingHorizontal:spacing.lg,paddingBottom:110,gap:12},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,flexDirection:'row',alignItems:'flex-start',gap:12},code:{fontSize:12,fontWeight:'900',color:colors.primary},name:{fontSize:16,fontWeight:'800',color:colors.text,marginTop:4},meta:{fontSize:12,color:colors.muted,marginTop:5},empty:{alignItems:'center',gap:10,paddingTop:80},emptyText:{color:colors.muted},fab:{position:'absolute',left:16,right:16,bottom:12}})
