import { LogOut, MapPin, ShieldCheck, UserRound } from 'lucide-react-native'
import { useRouter } from 'expo-router'
import { ScrollView, StyleSheet, Text, View } from 'react-native'
import { useAuth } from '../../src/auth/AuthContext'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import { colors, radius, spacing } from '../../src/styles/theme'
export default function ProfileScreen(){const {user,logout}=useAuth();const router=useRouter();const exit=async()=>{await logout();router.replace('/login')};return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader title="Profil" subtitle="Compte de l’agent recenseur"/><View style={styles.profile}><View style={styles.avatar}><UserRound color={colors.primary} size={48}/></View><Text style={styles.name}>{user?.fullName}</Text><Text style={styles.email}>{user?.email}</Text></View><View style={styles.card}><Info icon={ShieldCheck} label="Rôle" value={user?.role??'—'}/><Info icon={MapPin} label="Zone administrative" value={user?.administrativeAreaId??'Non affectée'}/></View><PrimaryButton title="Se déconnecter" icon={LogOut} secondary onPress={()=>void exit()}/></ScrollView>}
function Info({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <View style={styles.info}><View style={styles.infoIcon}><Icon color={colors.primary} size={19}/></View><View style={{flex:1}}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.lg,paddingBottom:96},profile:{alignItems:'center',backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.xl,padding:spacing.xl},avatar:{width:96,height:96,borderRadius:48,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},name:{fontSize:20,fontWeight:'900',color:colors.text,marginTop:14},email:{fontSize:12,color:colors.muted,marginTop:4},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:18},info:{flexDirection:'row',alignItems:'center',gap:12},infoIcon:{width:40,height:40,borderRadius:12,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},infoLabel:{fontSize:11,color:colors.muted},infoValue:{fontSize:13,fontWeight:'800',color:colors.text,marginTop:3}})
