import NetInfo from '@react-native-community/netinfo'
import { useFocusEffect } from 'expo-router'
import { AlertCircle, CheckCircle2, CloudUpload, Database, FileImage, RefreshCw, WifiOff } from 'lucide-react-native'
import { useCallback, useState } from 'react'
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import { getQueue, type QueueItem } from '../../src/storage/database'
import { syncPending } from '../../src/sync/syncService'
import { colors, radius, spacing } from '../../src/styles/theme'
export default function SyncScreen(){const [items,setItems]=useState<QueueItem[]>([]);const [online,setOnline]=useState<boolean|null>(null);const [syncing,setSyncing]=useState(false);const [progress,setProgress]=useState(0);const load=useCallback(async()=>{setItems(await getQueue());setOnline((await NetInfo.fetch()).isConnected)},[]);useFocusEffect(useCallback(()=>{void load()},[load]));const start=async()=>{setSyncing(true);setProgress(0);try{const result=await syncPending((done,total)=>setProgress(total?done/total:1));await load();if(result.errors===0)setProgress(1)}finally{setSyncing(false)}};const failed=items.filter(i=>i.status==='failed').length;return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader title="Synchronisation" subtitle={online?'Connexion disponible':'Mode hors ligne'}/><View style={[styles.cloud,online?styles.cloudOnline:styles.cloudOffline]}>{online?<CloudUpload color={colors.primary} size={54}/>:<WifiOff color={colors.warning} size={54}/>}<Text style={styles.cloudTitle}>{syncing?'Synchronisation en cours…':items.length?'Données en attente':'Tout est synchronisé'}</Text><Text style={styles.cloudText}>{items.length} opération(s) locale(s)</Text>{syncing&&<View style={styles.progress}><View style={[styles.fill,{width:`${Math.round(progress*100)}%`}]}/></View>}</View><View style={styles.stats}><Stat icon={Database} label="Données" value={`${items.length}`} color={colors.primary}/><Stat icon={FileImage} label="Fichiers" value="0" color="#8B5CF6"/><Stat icon={AlertCircle} label="Erreurs" value={`${failed}`} color={colors.danger}/></View><PrimaryButton title={items.length?'Synchroniser maintenant':'Actualiser'} icon={items.length?RefreshCw:CheckCircle2} loading={syncing} disabled={!online} onPress={()=>void(items.length?start():load())}/>{items.map(item=><View key={item.id} style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{item.payload.household.referenceCode}</Text><Text style={styles.itemText}>{item.status} · {new Date(item.createdAt).toLocaleString('fr-FR')}</Text>{item.lastError&&<Text style={styles.itemError}>{item.lastError}</Text>}</View></View>)}</ScrollView>}
function Stat({icon:Icon,label,value,color}:{icon:any;label:string;value:string;color:string}){return <View style={styles.stat}><Icon color={color} size={20}/><View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.lg,paddingBottom:96},cloud:{alignItems:'center',padding:spacing.xxl,borderRadius:radius.xl,borderWidth:1},cloudOnline:{backgroundColor:colors.primarySoft,borderColor:'#BFDBFE'},cloudOffline:{backgroundColor:colors.warningSoft,borderColor:'#FDE68A'},cloudTitle:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:14},cloudText:{fontSize:12,color:colors.muted,marginTop:4},progress:{width:'100%',height:7,backgroundColor:colors.white,borderRadius:999,marginTop:18,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.primary},stats:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:14},stat:{flexDirection:'row',alignItems:'center',gap:12},statLabel:{fontSize:12,color:colors.muted},statValue:{fontSize:16,fontWeight:'900',color:colors.text},item:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.lg,flexDirection:'row'},itemTitle:{fontWeight:'800',color:colors.text},itemText:{fontSize:11,color:colors.muted,marginTop:4},itemError:{fontSize:11,color:colors.danger,marginTop:5}})
