import { useRouter } from 'expo-router'
import { ArrowLeft, CheckCircle2, Eye, EyeOff, KeyRound, Mail, ShieldCheck } from 'lucide-react-native'
import { useState } from 'react'
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { messageFromError } from '../src/api/client'
import { mobileApi } from '../src/api/resources'
import PrimaryButton from '../src/components/PrimaryButton'
import { colors, radius, shadow, spacing } from '../src/styles/theme'

type Step='email'|'otp'|'password'|'done'
export default function ForgotPasswordScreen(){
 const router=useRouter();const[step,setStep]=useState<Step>('email');const[email,setEmail]=useState('');const[otp,setOtp]=useState('');const[token,setToken]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[show,setShow]=useState(false);const[devOtp,setDevOtp]=useState<string|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('')
 const request=async()=>{setLoading(true);setError('');try{const r=await mobileApi.requestPasswordCode(email.trim());setDevOtp(r.developmentOtp??null);setStep('otp')}catch(e){setError(messageFromError(e))}finally{setLoading(false)}}
 const verify=async()=>{setLoading(true);setError('');try{const r=await mobileApi.verifyPasswordCode(email.trim(),otp);setToken(r.resetToken);setStep('password')}catch(e){setError(messageFromError(e))}finally{setLoading(false)}}
 const reset=async()=>{if(password!==confirm){setError('Les mots de passe ne correspondent pas.');return}setLoading(true);setError('');try{await mobileApi.resetPassword(email.trim(),token,password,confirm);setStep('done')}catch(e){setError(messageFromError(e))}finally{setLoading(false)}}
 return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.card}><Pressable style={styles.back} onPress={()=>router.back()}><ArrowLeft color={colors.textSoft} size={18}/><Text style={styles.backText}>Retour</Text></Pressable><View style={styles.head}><View style={styles.icon}><KeyRound color={colors.primary} size={24}/></View><Text style={styles.title}>Récupérer mon accès</Text><Text style={styles.subtitle}>Trois étapes simples et sécurisées.</Text></View>
 {step==='email'&&<View style={styles.form}><Mail color={colors.primary} size={28}/><Text style={styles.formTitle}>Votre adresse e-mail</Text><TextInput style={styles.input} autoFocus value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="agent@recensement.mg" placeholderTextColor={colors.muted}/>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton title="Recevoir le code" loading={loading} onPress={request}/></View>}
 {step==='otp'&&<View style={styles.form}><ShieldCheck color={colors.primary} size={28}/><Text style={styles.formTitle}>Code de vérification</Text>{devOtp?<View style={styles.dev}><Text style={styles.devText}>Code local : {devOtp}</Text></View>:null}<TextInput style={[styles.input,styles.otp]} autoFocus value={otp} onChangeText={v=>setOtp(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" placeholder="000000" placeholderTextColor={colors.muted}/>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton title="Vérifier" loading={loading} disabled={otp.length!==6} onPress={verify}/></View>}
 {step==='password'&&<View style={styles.form}><KeyRound color={colors.primary} size={28}/><Text style={styles.formTitle}>Nouveau mot de passe</Text><View style={styles.password}><TextInput style={styles.passwordInput} autoFocus value={password} onChangeText={setPassword} secureTextEntry={!show} placeholder="Au moins 12 caractères" placeholderTextColor={colors.muted}/><Pressable onPress={()=>setShow(v=>!v)}>{show?<EyeOff color={colors.muted} size={18}/>:<Eye color={colors.muted} size={18}/>}</Pressable></View><TextInput style={styles.input} value={confirm} onChangeText={setConfirm} secureTextEntry={!show} placeholder="Confirmer le mot de passe" placeholderTextColor={colors.muted}/>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton title="Modifier le mot de passe" loading={loading} disabled={password.length<12} onPress={reset}/></View>}
 {step==='done'&&<View style={styles.done}><View style={styles.success}><CheckCircle2 color={colors.success} size={38}/></View><Text style={styles.formTitle}>Mot de passe modifié</Text><Text style={styles.subtitle}>Vous pouvez maintenant vous reconnecter.</Text><PrimaryButton title="Revenir à la connexion" onPress={()=>router.replace('/login')}/></View>}
 </View></ScrollView></KeyboardAvoidingView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{flexGrow:1,justifyContent:'center',padding:spacing.xl},card:{backgroundColor:colors.white,borderRadius:radius.xl,padding:spacing.xl,borderWidth:1,borderColor:colors.border,...shadow},back:{flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800',color:colors.textSoft},head:{alignItems:'center',marginTop:spacing.xl},icon:{width:54,height:54,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:colors.primarySoft},title:{fontSize:25,fontWeight:'900',color:colors.text,marginTop:13},subtitle:{color:colors.muted,textAlign:'center',marginTop:6},form:{gap:spacing.lg,marginTop:spacing.xxl},formTitle:{fontSize:20,fontWeight:'900',color:colors.text},input:{minHeight:52,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,color:colors.text,backgroundColor:colors.white},otp:{fontSize:25,fontWeight:'900',letterSpacing:8,textAlign:'center'},password:{minHeight:52,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,flexDirection:'row',alignItems:'center'},passwordInput:{flex:1,color:colors.text},error:{color:colors.danger,backgroundColor:colors.dangerSoft,padding:12,borderRadius:radius.sm},dev:{backgroundColor:colors.warningSoft,borderRadius:radius.md,padding:12},devText:{color:'#80570f',fontWeight:'800',textAlign:'center'},done:{alignItems:'center',gap:spacing.lg,marginTop:spacing.xxl},success:{width:72,height:72,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:colors.successSoft}})
