import { useFocusEffect, useRouter } from 'expo-router'
import { ArrowRight, BarChart3, Building2, CloudOff, MapPinned, Plus, RefreshCw, ScanLine, Users, UsersRound } from 'lucide-react-native'
import { useCallback, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { mobileApi } from '../../src/api/resources'
import { useAuth } from '../../src/auth/AuthContext'
import MetricCard from '../../src/components/MetricCard'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import { getQueue } from '../../src/storage/database'
import { colors, radius, shadow, spacing } from '../../src/styles/theme'
import type { CampaignDto, DashboardDto } from '../../src/types/api'

export default function HomeScreen(){
  const router=useRouter(); const {user}=useAuth(); const [campaign,setCampaign]=useState<CampaignDto|null>(null); const [dashboard,setDashboard]=useState<DashboardDto|null>(null); const [pending,setPending]=useState(0); const [loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setLoading(true);try{const campaigns=await mobileApi.campaigns();const active=campaigns.find(item=>item.status==='Active')??campaigns[0]??null;setCampaign(active);if(active)setDashboard(await mobileApi.dashboard(active.id));setPending((await getQueue()).length)}finally{setLoading(false)}},[])
  useFocusEffect(useCallback(()=>{void load()},[load]))
  if(loading)return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary}/></View>
  const validationRate=dashboard?.totalHouseholds?Math.round((dashboard.validatedHouseholds/dashboard.totalHouseholds)*100):0
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <ScreenHeader title={`Bonjour, ${user?.firstName ?? 'Agent'}`} subtitle={campaign?`${campaign.name} · ${campaign.status}`:'Aucune campagne active'} right={<Pressable style={styles.scanButton} onPress={()=>router.push('/scan')}><ScanLine color={colors.primary} size={21}/></Pressable>}/>
    <View style={styles.hero}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>Ménages validés</Text><Text style={styles.heroValue}>{validationRate}%</Text></View><View style={styles.heroBadge}><Text style={styles.heroBadgeText}>{dashboard?.totalHouseholds??0} ménages</Text></View></View><View style={styles.progress}><View style={[styles.progressFill,{width:`${validationRate}%`}]}/></View><Text style={styles.heroHint}>Continuez la collecte ou synchronisez les données en attente.</Text></View>
    <View style={styles.primaryAction}><PrimaryButton title="Commencer une collecte" icon={Plus} onPress={()=>router.push('/households/new')}/></View>
    <View style={styles.metrics}><MetricCard label="Habitations" value={dashboard?.totalDwellings??0} icon={Building2}/><MetricCard label="Ménages" value={dashboard?.totalHouseholds??0} icon={UsersRound} tone={colors.success}/><MetricCard label="Personnes" value={dashboard?.totalPersons??0} icon={Users} tone={colors.primary}/><MetricCard label="À synchroniser" value={pending} icon={CloudOff} tone={colors.warning}/></View>
    <Text style={styles.sectionTitle}>Actions utiles</Text>
    <View style={styles.quickGrid}><Pressable style={styles.quickCard} onPress={()=>router.push('/(tabs)/sync')}><View style={[styles.quickIcon,{backgroundColor:colors.primarySoft}]}><RefreshCw color={colors.primary} size={21}/></View><Text style={styles.quickTitle}>Synchroniser</Text><Text style={styles.quickText}>{pending} élément(s) en attente</Text><ArrowRight color={colors.muted} size={17}/></Pressable><Pressable style={styles.quickCard} onPress={()=>router.push('/(tabs)/map')}><View style={[styles.quickIcon,{backgroundColor:colors.accentSoft}]}><MapPinned color={colors.accent} size={21}/></View><Text style={styles.quickTitle}>Voir la carte</Text><Text style={styles.quickText}>Localiser les ménages</Text><ArrowRight color={colors.muted} size={17}/></Pressable><Pressable style={styles.quickCard} onPress={()=>router.push('/statistics')}><View style={[styles.quickIcon,{backgroundColor:colors.primarySoft}]}><BarChart3 color={colors.primary} size={21}/></View><Text style={styles.quickTitle}>Statistiques</Text><Text style={styles.quickText}>Consulter les données validées</Text><ArrowRight color={colors.muted} size={17}/></Pressable></View>
  </ScrollView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.lg,paddingBottom:112},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},scanButton:{width:44,height:44,borderRadius:14,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},hero:{backgroundColor:colors.navy,borderRadius:radius.xl,padding:spacing.xl,...shadow},heroTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},heroLabel:{color:'#B7C2D8',fontSize:12},heroValue:{color:colors.white,fontSize:38,fontWeight:'900',marginTop:4},heroBadge:{backgroundColor:'rgba(255,255,255,.09)',borderRadius:999,paddingHorizontal:12,paddingVertical:7},heroBadgeText:{color:'#DDE4F2',fontSize:11,fontWeight:'800'},progress:{height:8,borderRadius:999,backgroundColor:'rgba(255,255,255,.14)',marginTop:18,overflow:'hidden'},progressFill:{height:'100%',backgroundColor:colors.accent,borderRadius:999},heroHint:{color:'#9BA8C0',fontSize:11,marginTop:12},primaryAction:{marginTop:-4},metrics:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:12},sectionTitle:{fontSize:17,fontWeight:'900',color:colors.text,marginTop:2},quickGrid:{gap:12},quickCard:{display:'flex',flexDirection:'row',alignItems:'center',gap:12,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,...shadow},quickIcon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},quickTitle:{position:'absolute',left:72,top:16,fontWeight:'900',color:colors.text},quickText:{flex:1,marginLeft:0,paddingTop:22,fontSize:11,color:colors.muted}})
