import NetInfo from '@react-native-community/netinfo'
import { useFocusEffect } from 'expo-router'
import { AlertCircle, CheckCircle2, CloudUpload, Database, RefreshCw, UsersRound, WifiOff } from 'lucide-react-native'
import { useCallback, useState } from 'react'
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from 'react-native'
import PrimaryButton from '../../src/components/PrimaryButton'
import ScreenHeader from '../../src/components/ScreenHeader'
import { getQueue, markPending, type QueueItem } from '../../src/storage/database'
import { syncPending } from '../../src/sync/syncService'
import { colors, radius, spacing } from '../../src/styles/theme'
import { usePreferences } from '../../src/preferences/PreferencesContext'

export default function SyncScreen(){const {t}=usePreferences();const [items,setItems]=useState<QueueItem[]>([]);const [online,setOnline]=useState<boolean|null>(null);const [syncing,setSyncing]=useState(false);const [progress,setProgress]=useState(0);const load=useCallback(async()=>{setItems(await getQueue());setOnline((await NetInfo.fetch()).isConnected)},[]);useFocusEffect(useCallback(()=>{void load()},[load]));const start=async()=>{setSyncing(true);setProgress(0);for(const item of items)if(item.status==='failed')await markPending(item.id);try{const result=await syncPending((done,total)=>setProgress(total?done/total:1));await load();if(result.errors===0)setProgress(1)}finally{setSyncing(false)}};const failed=items.filter((item)=>item.status==='failed').length;const citizens=items.reduce((sum,item)=>sum+item.payload.persons.length,0);return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><ScreenHeader title={t('globalSync')} subtitle={online?t('networkReady'):t('offlineProtected')}/><View style={[styles.cloud,online?styles.cloudOnline:styles.cloudOffline]}>{online?<CloudUpload color={colors.primary} size={54}/>:<WifiOff color={colors.warning} size={54}/>}<Text style={styles.cloudTitle}>{syncing?t('sendingData'):items.length?t('localReady'):t('allSynced')}</Text><Text style={styles.cloudText}>{t('statsWaitValidation')}</Text>{syncing&&<View style={styles.progress}><View style={[styles.fill,{width:`${Math.round(progress*100)}%`}]}/></View>}</View><View style={styles.stats}><Stat icon={Database} label={t('localHouseholds')} value={`${items.length}`} color={colors.primary}/><Stat icon={UsersRound} label={t('localCitizens')} value={`${citizens}`} color={colors.accent}/><Stat icon={AlertCircle} label={t('errors')} value={`${failed}`} color={colors.danger}/></View><PrimaryButton title={items.length?t('syncNow'):t('refresh')} icon={items.length?RefreshCw:CheckCircle2} loading={syncing} disabled={!online} onPress={()=>void(items.length?start():load())}/>{items.map((item)=><View key={item.id} style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{item.payload.household.referenceCode} · {item.payload.location.fokontanyName}</Text><Text style={styles.itemText}>{item.payload.persons.length} {t('citizenCount')} · {item.status} · {new Date(item.createdAt).toLocaleString('fr-FR')}</Text>{item.lastError&&<Text style={styles.itemError}>{item.lastError}</Text>}</View></View>)}</ScrollView>}
function Stat({icon:Icon,label,value,color}:{icon:typeof Database;label:string;value:string;color:string}){return <View style={styles.stat}><Icon color={color} size={20}/><View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,gap:spacing.lg,paddingBottom:110},cloud:{alignItems:'center',padding:spacing.xxl,borderRadius:radius.xl,borderWidth:1},cloudOnline:{backgroundColor:colors.primarySoft,borderColor:colors.primary},cloudOffline:{backgroundColor:colors.warningSoft,borderColor:colors.warning},cloudTitle:{fontSize:18,fontWeight:'900',color:colors.text,marginTop:14},cloudText:{fontSize:11,lineHeight:17,color:colors.muted,marginTop:6,textAlign:'center'},progress:{width:'100%',height:7,backgroundColor:colors.white,borderRadius:999,marginTop:18,overflow:'hidden'},fill:{height:'100%',backgroundColor:colors.primary},stats:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg,gap:14},stat:{flexDirection:'row',alignItems:'center',gap:12},statLabel:{fontSize:11,color:colors.muted},statValue:{fontSize:16,fontWeight:'900',color:colors.text},item:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,padding:spacing.lg,flexDirection:'row'},itemTitle:{fontWeight:'800',color:colors.text},itemText:{fontSize:10,color:colors.muted,marginTop:4},itemError:{fontSize:10,color:colors.danger,marginTop:5}})
