import { useRouter } from 'expo-router'
import { Eye, EyeOff, LockKeyhole } from 'lucide-react-native'
import { useEffect, useRef, useState } from 'react'
import { Animated, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { messageFromError } from '../src/api/client'
import { runFadeUp } from '../src/animations/motion'
import { useAuth } from '../src/auth/AuthContext'
import Brand from '../src/components/Brand'
import PrimaryButton from '../src/components/PrimaryButton'
import { colors, radius, spacing } from '../src/styles/theme'
export default function LoginScreen(){const router=useRouter();const {login}=useAuth();const [email,setEmail]=useState('admin@gmail.com');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const opacity=useRef(new Animated.Value(0)).current;const translate=useRef(new Animated.Value(18)).current;useEffect(()=>runFadeUp(opacity,translate),[opacity,translate]);const submit=async()=>{setLoading(true);setError('');try{await login(email,password);router.replace('/(tabs)')}catch(e){setError(messageFromError(e))}finally{setLoading(false)}};return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Animated.View style={[styles.card,{opacity,transform:[{translateY:translate}]}]}><Brand/><View style={styles.intro}><Text style={styles.title}>Bienvenue</Text><Text style={styles.subtitle}>Connectez-vous à votre compte pour commencer la collecte.</Text></View><View><Text style={styles.label}>Email</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="agent@recensement.mg"/></View><View><Text style={styles.label}>Mot de passe</Text><View style={styles.password}><LockKeyhole color={colors.muted} size={18}/><TextInput style={styles.passwordInput} value={password} onChangeText={setPassword} secureTextEntry={!show} placeholder="••••••••••••"/><Pressable onPress={()=>setShow(v=>!v)}>{show?<EyeOff color={colors.muted} size={18}/>:<Eye color={colors.muted} size={18}/>}</Pressable></View></View>{error?<Text style={styles.error}>{error}</Text>:null}<PrimaryButton title="Se connecter" loading={loading} onPress={submit}/><Text style={styles.help}>Mot de passe oublié ? Contactez votre responsable.</Text></Animated.View></ScrollView></KeyboardAvoidingView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#F6F9FF'},content:{flexGrow:1,justifyContent:'center',padding:spacing.xl},card:{backgroundColor:colors.white,borderRadius:radius.xl,padding:spacing.xl,gap:spacing.lg,borderWidth:1,borderColor:colors.border},intro:{marginTop:spacing.lg},title:{fontSize:28,fontWeight:'900',color:colors.text},subtitle:{color:colors.muted,marginTop:6,lineHeight:20},label:{fontSize:12,fontWeight:'800',color:colors.textSoft,marginBottom:7},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,color:colors.text},password:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:9},passwordInput:{flex:1,color:colors.text},error:{color:colors.danger,backgroundColor:colors.dangerSoft,padding:12,borderRadius:radius.sm},help:{textAlign:'center',fontSize:11,color:colors.primary}})
