import NetInfo from '@react-native-community/netinfo'
import * as ImagePicker from 'expo-image-picker'
import * as Location from 'expo-location'
import { useRouter } from 'expo-router'
import { Building2, Camera, Check, ChevronLeft, ChevronRight, LocateFixed, UserPlus, UsersRound } from 'lucide-react-native'
import { useEffect, useMemo, useState } from 'react'
import { Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { messageFromError } from '../../src/api/client'
import { mobileApi } from '../../src/api/resources'
import FormField from '../../src/components/FormField'
import PrimaryButton from '../../src/components/PrimaryButton'
import SelectField from '../../src/components/SelectField'
import { enqueueBundle } from '../../src/storage/database'
import { colors, radius, shadow, spacing } from '../../src/styles/theme'
import type { AdministrativeAreaDto, CampaignDto, CensusBundle } from '../../src/types/api'

const randomCode=(prefix:string)=>`${prefix}-${new Date().getFullYear()}-${Math.floor(1000+Math.random()*9000)}`
const steps=[{title:'Habitation',caption:'Localisation',icon:Building2},{title:'Ménage',caption:'Informations',icon:UsersRound},{title:'Chef',caption:'Premier membre',icon:UserPlus}]

export default function NewHouseholdScreen(){
  const router=useRouter();const [step,setStep]=useState(1);const [campaigns,setCampaigns]=useState<CampaignDto[]>([]);const [zones,setZones]=useState<AdministrativeAreaDto[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const [campaignId,setCampaignId]=useState('');const [zoneId,setZoneId]=useState('');const [latitude,setLatitude]=useState('');const [longitude,setLongitude]=useState('');const [address,setAddress]=useState('');const [locality,setLocality]=useState('');const [photoUri,setPhotoUri]=useState<string|null>(null)
  const [householdCode,setHouseholdCode]=useState(()=>randomCode('MNG'));const [householdType,setHouseholdType]=useState('Ordinary');const [headFullName,setHeadFullName]=useState('');const [phone,setPhone]=useState('')
  const [firstName,setFirstName]=useState('');const [lastName,setLastName]=useState('');const [sex,setSex]=useState('Female');const [dateOfBirth,setDateOfBirth]=useState('');const [age,setAge]=useState('');const [relationship,setRelationship]=useState('Head');const [maritalStatus,setMaritalStatus]=useState('Single');const [occupation,setOccupation]=useState('')

  useEffect(()=>{void Promise.all([mobileApi.campaigns(),mobileApi.zones()]).then(([c,z])=>{setCampaigns(c);setZones(z);setCampaignId(c.find(x=>x.status==='Active')?.id??c[0]?.id??'');setZoneId(z[0]?.id??'')}).catch(e=>setError(messageFromError(e)))},[])

  const locate=async()=>{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){Alert.alert('Permission refusée','Autorisez la localisation pour enregistrer précisément le ménage.');return}const point=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setLatitude(String(point.coords.latitude));setLongitude(String(point.coords.longitude))}
  const photo=async()=>{const permission=await ImagePicker.requestCameraPermissionsAsync();if(!permission.granted){Alert.alert('Permission refusée','Autorisez la caméra pour prendre une photo.');return}const result=await ImagePicker.launchCameraAsync({quality:.7,allowsEditing:true});if(!result.canceled)setPhotoUri(result.assets[0].uri)}
  const canNext=useMemo(()=>step===1?Boolean(campaignId&&zoneId&&latitude&&longitude):step===2?Boolean(householdCode&&headFullName):Boolean(firstName&&lastName),[step,campaignId,zoneId,latitude,longitude,householdCode,headFullName,firstName,lastName])

  const save=async()=>{setSaving(true);setError('');const bundle:CensusBundle={localId:`${Date.now()}-${Math.random().toString(36).slice(2)}`,campaignId,enumerationAreaId:zoneId,dwelling:{referenceCode:randomCode('HAB'),address,localityName:locality,latitude:Number(latitude),longitude:Number(longitude),photoUri},household:{referenceCode:householdCode,householdType,headFullName,phoneNumber:phone},person:{personNumber:1,firstName,lastName,sex,dateOfBirth:dateOfBirth||null,ageYears:age?Number(age):null,relationshipToHead:relationship,maritalStatus,nationality:'Malagasy',occupation}}
    try{const network=await NetInfo.fetch();let queued=false;if(network.isConnected){try{await mobileApi.createBundle(bundle)}catch{await enqueueBundle(bundle);queued=true}}else{await enqueueBundle(bundle);queued=true}router.replace({pathname:'/confirmation',params:{code:householdCode,queued:String(queued)}})}catch(e){setError(messageFromError(e))}finally{setSaving(false)}}

  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS==='ios'?'padding':undefined}>
    <View style={styles.top}><Pressable style={styles.back} onPress={()=>step>1?setStep(s=>s-1):router.back()}><ChevronLeft color={colors.text} size={23}/></Pressable><View style={{flex:1}}><Text style={styles.title}>Nouvelle collecte</Text><Text style={styles.subtitle}>Les données sont sauvegardées même hors connexion.</Text></View></View>
    <View style={styles.stepper}>{steps.map((item,index)=>{const Icon=item.icon;const number=index+1;const active=number===step;const done=number<step;return <Pressable key={item.title} style={[styles.stepItem,active&&styles.stepItemActive]} onPress={()=>done&&setStep(number)}><View style={[styles.stepIcon,(active||done)&&styles.stepIconActive]}>{done?<Check color={colors.white} size={16}/>:<Icon color={active?colors.white:colors.muted} size={17}/>}</View><View><Text style={[styles.stepTitle,active&&styles.stepTitleActive]}>{item.title}</Text><Text style={styles.stepCaption}>{item.caption}</Text></View></Pressable>})}</View>

    <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      <View style={styles.sectionCard}>
        {step===1&&<><View style={styles.sectionHead}><Building2 color={colors.primary} size={22}/><View><Text style={styles.sectionTitle}>Localiser l’habitation</Text><Text style={styles.sectionText}>Campagne, zone et coordonnées GPS.</Text></View></View><SelectField label="Campagne" value={campaignId} onChange={setCampaignId} options={campaigns.map(x=>({label:x.name,value:x.id}))}/><SelectField label="Zone de dénombrement" value={zoneId} onChange={setZoneId} options={zones.map(x=>({label:`${x.code} — ${x.name}`,value:x.id}))}/><FormField label="Localité" value={locality} onChangeText={setLocality} placeholder="Village, quartier ou secteur"/><FormField label="Adresse ou point de repère" value={address} onChangeText={setAddress} placeholder="Près de…"/><PrimaryButton title="Utiliser ma position GPS" icon={LocateFixed} secondary onPress={()=>void locate()}/>{latitude&&longitude?<View style={styles.locationOk}><Check color={colors.success} size={17}/><Text style={styles.locationOkText}>Position enregistrée : {Number(latitude).toFixed(5)}, {Number(longitude).toFixed(5)}</Text></View>:null}<Pressable style={styles.photo} onPress={()=>void photo()}>{photoUri?<Image source={{uri:photoUri}} style={styles.photoImage}/>:<><Camera color={colors.primary} size={30}/><Text style={styles.photoTitle}>Ajouter une photo</Text><Text style={styles.photoText}>Facultatif, utile pour retrouver l’habitation</Text></>}</Pressable></>}
        {step===2&&<><View style={styles.sectionHead}><UsersRound color={colors.primary} size={22}/><View><Text style={styles.sectionTitle}>Décrire le ménage</Text><Text style={styles.sectionText}>Seulement les informations essentielles.</Text></View></View><FormField label="Code ménage" value={householdCode} onChangeText={setHouseholdCode}/><SelectField label="Type de ménage" value={householdType} onChange={setHouseholdType} options={[{label:'Ordinaire',value:'Ordinary'},{label:'Collectif',value:'Collective'},{label:'Sans-abri',value:'Homeless'}]}/><FormField label="Nom complet du chef de ménage" value={headFullName} onChangeText={setHeadFullName} placeholder="Prénom et nom"/><FormField label="Téléphone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="Facultatif"/><View style={styles.tip}><UsersRound color={colors.primary} size={20}/><Text style={styles.tipText}>À l’étape suivante, vous enregistrerez le chef comme premier membre.</Text></View></>}
        {step===3&&<><View style={styles.sectionHead}><UserPlus color={colors.primary} size={22}/><View><Text style={styles.sectionTitle}>Enregistrer le chef</Text><Text style={styles.sectionText}>Les autres membres pourront être ajoutés ensuite.</Text></View></View><FormField label="Prénom" value={firstName} onChangeText={setFirstName}/><FormField label="Nom" value={lastName} onChangeText={setLastName}/><SelectField label="Sexe" value={sex} onChange={setSex} options={[{label:'Féminin',value:'Female'},{label:'Masculin',value:'Male'},{label:'Autre',value:'Other'},{label:'Non déclaré',value:'NotStated'}]}/><FormField label="Date de naissance" value={dateOfBirth} onChangeText={setDateOfBirth} placeholder="AAAA-MM-JJ"/><FormField label="Âge (si date inconnue)" value={age} onChangeText={setAge} keyboardType="number-pad"/><SelectField label="Lien avec le chef" value={relationship} onChange={setRelationship} options={[{label:'Chef de ménage',value:'Head'},{label:'Conjoint(e)',value:'Spouse'},{label:'Enfant',value:'Child'},{label:'Parent',value:'Parent'},{label:'Frère/Sœur',value:'Sibling'},{label:'Autre parent',value:'OtherRelative'},{label:'Sans lien',value:'NonRelative'}]}/><SelectField label="État matrimonial" value={maritalStatus} onChange={setMaritalStatus} options={[{label:'Célibataire',value:'Single'},{label:'Marié(e)',value:'Married'},{label:'Divorcé(e)',value:'Divorced'},{label:'Veuf/Veuve',value:'Widowed'},{label:'Séparé(e)',value:'Separated'},{label:'Non déclaré',value:'NotStated'}]}/><FormField label="Activité principale" value={occupation} onChangeText={setOccupation} placeholder="Facultatif"/></>}
        {error?<Text style={styles.error}>{error}</Text>:null}
      </View>
    </ScrollView>

    <View style={styles.footer}>{step>1?<Pressable style={styles.previous} onPress={()=>setStep(s=>s-1)}><ChevronLeft color={colors.textSoft} size={18}/><Text style={styles.previousText}>Précédent</Text></Pressable>:<View/>}{step<3?<View style={styles.next}><PrimaryButton title="Continuer" icon={ChevronRight} disabled={!canNext} onPress={()=>setStep(s=>s+1)}/></View>:<View style={styles.next}><PrimaryButton title="Enregistrer" icon={Check} disabled={!canNext} loading={saving} onPress={()=>void save()}/></View>}</View>
  </KeyboardAvoidingView>
}

const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},top:{flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:spacing.lg,paddingTop:spacing.lg,paddingBottom:12,backgroundColor:colors.white},back:{width:42,height:42,borderRadius:13,backgroundColor:colors.background,alignItems:'center',justifyContent:'center'},title:{fontSize:19,fontWeight:'900',color:colors.text},subtitle:{fontSize:10,color:colors.muted,marginTop:2},stepper:{flexDirection:'row',gap:7,paddingHorizontal:spacing.md,paddingVertical:10,backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.border},stepItem:{flex:1,flexDirection:'row',alignItems:'center',gap:6,borderRadius:radius.md,padding:7},stepItemActive:{backgroundColor:colors.primarySoft},stepIcon:{width:30,height:30,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},stepIconActive:{backgroundColor:colors.primary},stepTitle:{fontSize:10,fontWeight:'900',color:colors.textSoft},stepTitleActive:{color:colors.primary},stepCaption:{fontSize:8,color:colors.muted},content:{padding:spacing.lg,paddingBottom:30},sectionCard:{gap:spacing.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.xl,padding:spacing.lg,...shadow},sectionHead:{flexDirection:'row',alignItems:'center',gap:11,paddingBottom:spacing.md,borderBottomWidth:1,borderBottomColor:colors.border},sectionTitle:{fontSize:17,fontWeight:'900',color:colors.text},sectionText:{fontSize:10,color:colors.muted,marginTop:2},photo:{minHeight:150,borderWidth:1,borderStyle:'dashed',borderColor:colors.border,borderRadius:radius.lg,backgroundColor:colors.background,alignItems:'center',justifyContent:'center',overflow:'hidden'},photoImage:{width:'100%',height:190},photoTitle:{fontWeight:'900',color:colors.text,marginTop:9},photoText:{color:colors.muted,marginTop:3,fontSize:10},locationOk:{flexDirection:'row',alignItems:'center',gap:8,backgroundColor:colors.successSoft,borderRadius:radius.md,padding:12},locationOkText:{flex:1,color:colors.textSoft,fontSize:10},tip:{flexDirection:'row',gap:10,backgroundColor:colors.primarySoft,borderRadius:radius.md,padding:14},tipText:{flex:1,color:colors.textSoft,fontSize:11,lineHeight:17},error:{color:colors.danger,backgroundColor:colors.dangerSoft,padding:12,borderRadius:radius.sm},footer:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,padding:spacing.lg,backgroundColor:colors.white,borderTopWidth:1,borderTopColor:colors.border},previous:{flexDirection:'row',alignItems:'center',gap:5,padding:12},previousText:{fontWeight:'800',color:colors.textSoft},next:{minWidth:180}})
